# Generated by Django 3.1.7 on 2021-04-03 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('device_ID', models.CharField(blank=True, max_length=20, null=True, verbose_name='Device ID')),
                ('device_KEY', models.CharField(blank=True, max_length=20, null=True, verbose_name='Device KEY')),
                ('situacao', models.CharField(choices=[('Vendido', 'Vendido'), ('Estoque', 'Estoque'), ('Defeito', 'Defeito'), ('Comprador', 'Comprador')], default='Estoque', max_length=15, verbose_name='Situação')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Box', 'Box'), ('TV', 'TV'), ('Celular', 'Celular')], default='Box', max_length=15, verbose_name='Tipo')),
                ('pagamento', models.CharField(choices=[('50%', '50%'), ('100%', '100%')], default='100%', max_length=15, verbose_name='Pagamento')),
                ('aplicativo', models.CharField(choices=[('OK', 'OK'), ('Grátis', 'Grátis'), ('50%', '50%')], default='Ok', max_length=15, verbose_name='App')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente')),
                ('produto', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
            ],
        ),
    ]
