# Generated by Django 3.1.7 on 2021-03-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Produto')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('Device_ID', models.CharField(max_length=100, verbose_name='Device ID')),
                ('Device_KEY', models.CharField(max_length=100, verbose_name='Device KEY')),
                ('situacao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Situação')),
                ('pagamento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Pagamento')),
                ('app', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='App')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
    ]
