# Generated by Django 3.1.7 on 2021-03-27 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('core', '0002_auto_20210327_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='Device_ID',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='Device_KEY',
        ),
        migrations.AddField(
            model_name='venda',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente'),
        ),
        migrations.AddField(
            model_name='venda',
            name='device_ID',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Device ID'),
        ),
        migrations.AddField(
            model_name='venda',
            name='device_KEY',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Device KEY'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='app',
            field=models.CharField(choices=[('O', 'Ok'), ('G', 'gratis'), ('1', '50%')], default='Ok', max_length=1, verbose_name='App'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='marca',
            field=models.CharField(max_length=30, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='pagamento',
            field=models.CharField(choices=[('1', '50%'), ('2', '100%')], default='100%', max_length=1, verbose_name='Pagamento'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='situacao',
            field=models.CharField(choices=[('V', 'Vendido'), ('E', 'Estoque'), ('D', 'Defeito')], default='Estoque', max_length=1, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='tipo',
            field=models.CharField(choices=[('B', 'Box'), ('T', 'Tv'), ('C', 'Celular')], default='Box', max_length=1, verbose_name='Tipo'),
        ),
    ]
