# Generated by Django 3.1.7 on 2021-04-04 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210404_0713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='dispositivo',
            new_name='produto',
        ),
    ]
