# Generated by Django 3.1.7 on 2021-03-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210327_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='cliente',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cliente'),
        ),
    ]
