# Generated by Django 3.1.7 on 2021-03-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210327_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='app',
            field=models.CharField(choices=[('O', 'OK'), ('G', 'Grátis'), ('1', '50%')], default='Ok', max_length=1, verbose_name='App'),
        ),
    ]
