# Generated by Django 3.1.7 on 2021-04-14 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210404_0718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True, verbose_name='Nome')),
                ('identificador', models.CharField(blank=True, max_length=100, verbose_name='Autentificador')),
                ('situacao', models.CharField(choices=[('Vendido', 'Vendido'), ('Estoque', 'Estoque'), ('Defeito', 'Defeito')], default='Estoque', max_length=15, verbose_name='Situação')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.RemoveField(
            model_name='dispositivos',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='dispositivos',
            name='situacao',
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.box'),
        ),
    ]
