# Generated by Django 3.1.7 on 2021-04-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210414_0557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='situacao',
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='situacao',
            field=models.CharField(choices=[('Vendido', 'Vendido'), ('Estoque', 'Estoque'), ('Defeito', 'Defeito'), ('Comprador', 'Comprador')], default='Estoque', max_length=15, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='box',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
