# Generated by Django 3.1.7 on 2021-04-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210414_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='nome',
            field=models.CharField(max_length=100, null=True, verbose_name='Nome'),
        ),
    ]
