# Generated by Django 3.1.7 on 2021-03-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_venda_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='marca',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Marca'),
        ),
    ]
