# Generated by Django 3.1.7 on 2021-04-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210414_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivos',
            name='device_ID',
            field=models.CharField(max_length=20, verbose_name='Device ID'),
        ),
        migrations.AlterField(
            model_name='dispositivos',
            name='device_KEY',
            field=models.CharField(max_length=20, verbose_name='Device KEY'),
        ),
    ]
