# Generated by Django 3.1.7 on 2021-03-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210327_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='app',
            field=models.CharField(choices=[('OK', 'OK'), ('Grátis', 'Grátis'), ('50%', '50%')], default='Ok', max_length=15, verbose_name='App'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='pagamento',
            field=models.CharField(choices=[('50%', '50%'), ('100%', '100%')], default='100%', max_length=15, verbose_name='Pagamento'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='situacao',
            field=models.CharField(choices=[('Vendido', 'Vendido'), ('Estoque', 'Estoque'), ('Defeito', 'Defeito')], default='Estoque', max_length=15, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='tipo',
            field=models.CharField(choices=[('Box', 'Box'), ('TV', 'TV'), ('Celular', 'Celular')], default='Box', max_length=15, verbose_name='Tipo'),
        ),
    ]
