# Generated by Django 3.1.7 on 2021-04-14 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210414_0747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='box',
        ),
        migrations.AddField(
            model_name='venda',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.dispositivos'),
        ),
    ]
